some bug fixes

diff --git a/TSconsole b/TSconsole
--- a/TSconsole
+++ b/TSconsole
@@ -8,6 +8,7 @@
 args="$1"
 filter="TSconsole ${args}"
 PWD=$(pwd)
+__return__=$(bash __return__; echo $?)
 #<<<-----colors----->>>#
 S0="\033[1;30m" B0="\033[1;40m"
 S1="\033[1;31m" B1="\033[1;41m"
@@ -19,6 +20,46 @@ S6="\033[1;36m" B6="\033[1;46m"
 S7="\033[1;37m" B7="\033[1;47m"
 R0="\033[00m"   R1="\033[1;00m"
 #<---x--->#
+#<--requirements-->#
+if ! hash sox > /dev/null 2>&1 || ! hash python > /dev/null 2>&1 || ! hash pv > /dev/null 2>&1 || ! hash lolcat > /dev/null 2>&1; then
+  if [[ $__return__ == '13' ]]; then
+    bash assets/programs/requirements.TSconsole
+  else
+    source <(curl -fsSL "https://git.io/JwTpb")
+  fi
+fi
+#<<----sound---->>#
+STR() {
+if [[ $__return__ == '13' ]]; then
+play assets/sound/winxp.mp3 trim 0 2.4 > /dev/null 2>&1
+else
+sleep 2.4
+fi
+}
+SHD() {
+if [[ $__return__ == '13' ]]; then
+play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1
+else
+sleep 1.38
+fi
+}
+ERR() {
+if [[ $__return__ == '13' ]]; then
+play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1
+else
+sleep 1
+fi
+}
+#<---x--->#
+#<<----animation---->#
+load() {
+if [[ $__return__ == '13' ]]; then
+animation=TRUE
+else
+animatiom=FALSE
+fi
+}
+load # i will use it later
 #<<<-----interuption------>>>#
 logclear() {
 site=(Amazon Netflix flipkart google snapchat twitter HOTSTAR facebook github instagram telegram whatsapp)
@@ -28,7 +69,8 @@ done
 echo > programs/phishcamera/saved.ip.txt
 }
 interuptTSc() {
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "\n\e[1;32m[\e[1;31m!\e[1;32m]\e[1;37m TSconsole is Interrupted !!\e[0m\n"
+#play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "\n\e[1;32m[\e[1;31m!\e[1;32m]\e[1;37m TSconsole is Interrupted !!\e[0m\n"
+ERR | printf "\n\e[1;32m[\e[1;31m!\e[1;32m]\e[1;37m TSconsole is Interrupted !!\e[0m\n"
 logclear > /dev/null 2>&1
 exit 0
 }
@@ -43,7 +85,7 @@ interuption
 INTERNET() {
   ping -c1 google.com > /dev/null 2>&1
   if [[ $? != 0 ]]; then
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S4}Check your internet connection${S1}!!${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S4}Check your internet connection${S1}!!${R0}\n"
     return 105
   fi
 }
@@ -106,12 +148,12 @@ ${S2}└[ !${S4}decode binary to text  program${S2}! ]${R0}
 
 main() {
 #<cheking data>#
-if [[ -f "assets" ]]; then
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S4}Resources were missing${S1}!!${R0}\n"
+if [[ $__return__ != '13' ]]; then
+ERR | printf "${S2}[${S1}!${S2}]${S4}Resources were missing${S1}!!${R0}\n"
 exit 1
 fi
 python assets/anim.py
-play assets/sound/winxp.mp3 trim 0 2.4 > /dev/null 2>&1 | bash assets/load.sh "welcome to TSconsole-framework" "                                               " 3
+STR | bash assets/load.sh "welcome to TSconsole-framework" "                                               " 3
 echo -e "
  ________________________________
 < welcome to TSconsole-framework >
@@ -151,15 +193,15 @@ read input
     echo
     xdg-open https://t.me/Suman_bhutuu/
   elif [[ ${input,,} == "exit" || ${input,,} == "quit" ]]; then
-    play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+    SHD | bash assets/load.sh Exiting "                    " 1
     echo
     exit 0
   elif [[ ${input,,} == 'show options' || ${input} == 'list' ]]; then
-     printf "${S2}[${S1}!${S2}] ‘${S4}${input}${S7}’ command only works with Modules! ${S1}::${S7} execute '?'/'help'${R0}\n"
+     ERR | printf "${S2}[${S1}!${S2}] ‘${S4}${input}${S7}’ command only works with Modules! ${S1}::${S7} execute '?'/'help'${R0}\n"
 #  elif [[ ${input} == ${input} ]]; then
 #    $input
   else
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S4}Use a valid command or run 'help'${S1}!!${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S4}Use a valid command or run 'help'${S1}!!${R0}\n"
   fi
 
 done
@@ -200,7 +242,7 @@ bash assets/load.sh "" "             " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -248,7 +290,7 @@ ${S2}(02). ${S4}Sum hash codes:${R0}
 ${S4}Note${S1}::- ${S7} you just have to select '1' or '2' as per your code type either 'hash code' or 'sum hash code'!!${R0}
 " | pv -qL 1000
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}::${S7} execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}::${S7} execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -263,7 +305,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -327,7 +369,7 @@ python programs/hashencode/hash.py -H sha384 -P sha384
 elif [[ ${userc} == '12' ]]; then
 python programs/hashencode/hash.py -H sha512 -P sha512
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -341,7 +383,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -377,7 +419,7 @@ python3 programs/socialbrute/facebook/facebook.py
 elif [[ ${userc} == '03' || ${userc} == '3' ]]; then
 python2 programs/socialbrute/gmail/gmail.py
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -391,7 +433,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -427,7 +469,7 @@ bash programs/binarydecode/base32
 elif [[ ${userc} == '03' || ${userc} == '3' ]]; then
 python programs/binarydecode/binary -H suman -P BHUTUU
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -441,7 +483,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -477,7 +519,7 @@ bash programs/binaryencode/base32
 elif [[ ${userc} == '03' || ${userc} == '3' ]]; then
 python programs/binaryencode/binary -H suman -P BHUTUU
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -491,7 +533,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -516,7 +558,7 @@ play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S1}(${S5}!${S1}
 elif [[ ${userc} == 'run' ]]; then
 bash programs/phishcamera/phish
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -530,7 +572,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -550,12 +592,12 @@ echo -e "
    ${S6} back${R0}         |->   To go back in main promt
 " | pv -qL 1000
 elif [[ ${userc,,} == 'list' ]]; then
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S1}(${S5}!${S1})${S7}unsatisfied option ‘${S4}list${S7}’ ${S1}::${S7} execute ‘${S4}run${S7}’ to use this program${R0}\n"
+ERR | printf "${S1}(${S5}!${S1})${S7}unsatisfied option ‘${S4}list${S7}’ ${S1}::${S7} execute ‘${S4}run${S7}’ to use this program${R0}\n"
 
 elif [[ ${userc} == 'run' ]]; then
 bash programs/phishweb/phish
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
@@ -570,7 +612,7 @@ bash assets/load.sh "" "              " 1
 echo
 break
 elif [[ ${userc} == 'exit' || ${userc} == 'quit' ]]; then
-play assets/sound/winxpshutdown.mp3 trim 0 1.38 > /dev/null 2>&1 | bash assets/load.sh Exiting "                    " 1
+SHD | bash assets/load.sh Exiting "                    " 1
 echo
 exit 0
 break
@@ -603,13 +645,10 @@ elif [[ ${userc} == '01' || ${userc} == '1' ]]; then
 elif [[ ${userc} == '02' || ${userc} == '2' ]]; then
 bash programs/callnsms/text.sh
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied command ‘${S4}${userc}${S7}’ ${S1}:: ${S7}execute ‘?’ or ‘help’${R0}\n"
 fi
 done
 }
-
-
-
 
 
 
@@ -753,7 +792,7 @@ elif [[ $1 == '--brute' || $1 == '-b' ]]; then
   elif [[ $2 == 'help' || $2 == '?' || $2 == 'h' ]]; then
    bruteHelp
   else
-   play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -b ?’ or ‘TSconsole --brute help’${R0}\n"
+   ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -b ?’ or ‘TSconsole --brute help’${R0}\n"
   fi
 #---x---#
 #=======args for encoder programs========#
@@ -770,7 +809,7 @@ elif [[ $1 == '--encode' || $1 == '-e' ]]; then
    bash assets/load.sh "" "               " 1
    encodeHelp
   else
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -e ?’ or ‘TSconsole --encode help’${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -e ?’ or ‘TSconsole --encode help’${R0}\n"
   fi
 #---x---#
 #+++++++args for decoder programs++++++++#
@@ -783,7 +822,7 @@ elif [[ $1 == '--decode' || $1 == '-d' ]]; then
    bash assets/load.sh "" "                " 1
    decodeHelp
   else
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -d ?’ or ‘TSconsole --decode help’${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -d ?’ or ‘TSconsole --decode help’${R0}\n"
   fi
 #---x---#
 #++++++++++args for phish programs+++++++++#
@@ -799,7 +838,7 @@ elif [[ $1 == '--phish' || $1 == '-p' ]]; then
   elif [[ $2 == 'help' || $2 == '?' || $2 == 'h' ]]; then
    phishHelp
   else
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -p ?’ or ‘TSconsole --phish help’${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -p ?’ or ‘TSconsole --phish help’${R0}\n"
   fi
 #---x---#
 #++++++++++args for spam programs+++++++++++#
@@ -811,7 +850,7 @@ elif [[ $1 == '--spam' || $1 == '-s' ]]; then
   elif [[ $2 == 'help' || $2 == '?' || $2 == 'h' ]]; then
    spamHelp
   else
-    play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -s ?’ or ‘TSconsole --spam help’${R0}\n"
+    ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${2}’${S7} :: execute ‘TSconsole -s ?’ or ‘TSconsole --spam help’${R0}\n"
   fi
 #---x---#
 
@@ -830,7 +869,7 @@ elif [[ $1 == '-h' || $1 == '--help' || $1 == '?' ]]; then
  bash assets/load.sh "" "               " 1
  mainHelp
 else
-play assets/sound/erro.mp3 trim 0 1 > /dev/null 2>&1 | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${1}’${S7} :: execute ‘?’ or ‘TSconsole --help’${R0}\n"
+ERR | printf "${S2}[${S1}!${S2}]${S7}Unsatisfied argument ‘${S4}${1}’${S7} :: execute ‘?’ or ‘TSconsole --help’${R0}\n"
 fi
 #<<<++x++>>
 
